export const averagesData = [
    { category: 'PPG', values: ['14.5'] },
    { category: 'APG', values: ['4.4'] },
    { category: '3PM', values: ['1.0'] },
    { category: 'RPG', values: ['6.5'] },
    { category: 'SPG', values: ['1.2'] },
    { category: 'BPG', values: ['0.6'] },
    { category: 'TPG', values: ['2.1'] },
    { category: 'FGA', values: ['11.3'] },
    { category: 'FGM', values: ['5.5'] },
    { category: 'FTA', values: ['3.4'] },
    { category: 'FTM', values: ['2.4'] },
]

export const myStatsData = {
    myTeam: {
        players: [
            {
                id: '9158',
                firstName: 'LeBron',
                lastName: 'James',
                fullName: 'LeBron James',
                currentTeam: { abbreviation: 'LAL', __typename: 'NbaTeam' },
                position: 'SF',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/2544.png',
                __typename: 'Player',
                stats: [
                    { category: 'FGA', value: 20.1, __typename: 'Stat' },
                    { category: 'FGM', value: 10, __typename: 'Stat' },
                    { category: 'FTA', value: 5.3, __typename: 'Stat' },
                    { category: 'FTM', value: 3.7, __typename: 'Stat' },
                    { category: '3PM', value: 2.2, __typename: 'Stat' },
                    { category: 'RPG', value: 7, __typename: 'Stat' },
                    { category: 'APG', value: 10.8, __typename: 'Stat' },
                    { category: 'PPG', value: 25.9, __typename: 'Stat' },
                    { category: 'SPG', value: 1.3, __typename: 'Stat' },
                    { category: 'BPG', value: 0.5, __typename: 'Stat' },
                    { category: 'TPG', value: 4, __typename: 'Stat' },
                ],
            },
            {
                id: '9082',
                firstName: 'Al',
                lastName: 'Horford',
                fullName: 'Al Horford',
                currentTeam: { abbreviation: 'PHI', __typename: 'NbaTeam' },
                position: 'C',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201143.png',
                __typename: 'Player',
                stats: [
                    { category: 'FGA', value: 11.7, __typename: 'Stat' },
                    { category: 'FGM', value: 5.6, __typename: 'Stat' },
                    { category: 'FTA', value: 1.6, __typename: 'Stat' },
                    { category: 'FTM', value: 1.1, __typename: 'Stat' },
                    { category: '3PM', value: 1.5, __typename: 'Stat' },
                    { category: 'RPG', value: 6.8, __typename: 'Stat' },
                    { category: 'APG', value: 3.9, __typename: 'Stat' },
                    { category: 'PPG', value: 13.8, __typename: 'Stat' },
                    { category: 'SPG', value: 1.2, __typename: 'Stat' },
                    { category: 'BPG', value: 1, __typename: 'Stat' },
                    { category: 'TPG', value: 1.2, __typename: 'Stat' },
                ],
            },
            {
                id: '9329',
                firstName: 'Jabari',
                lastName: 'Parker',
                fullName: 'Jabari Parker',
                currentTeam: { abbreviation: 'ATL', __typename: 'NbaTeam' },
                position: 'PF',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203953.png',
                __typename: 'Player',
                stats: [
                    { category: 'FGA', value: 13.1, __typename: 'Stat' },
                    { category: 'FGM', value: 6.7, __typename: 'Stat' },
                    { category: 'FTA', value: 2.5, __typename: 'Stat' },
                    { category: 'FTM', value: 1.8, __typename: 'Stat' },
                    { category: '3PM', value: 1, __typename: 'Stat' },
                    { category: 'RPG', value: 6.4, __typename: 'Stat' },
                    { category: 'APG', value: 1.8, __typename: 'Stat' },
                    { category: 'PPG', value: 16.1, __typename: 'Stat' },
                    { category: 'SPG', value: 1.4, __typename: 'Stat' },
                    { category: 'BPG', value: 0.5, __typename: 'Stat' },
                    { category: 'TPG', value: 2, __typename: 'Stat' },
                ],
            },
            {
                id: '9503',
                firstName: 'Rudy',
                lastName: 'Gobert',
                fullName: 'Rudy Gobert',
                currentTeam: { abbreviation: 'UTA', __typename: 'NbaTeam' },
                position: 'C',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203497.png',
                __typename: 'Player',
                stats: [
                    { category: 'FGA', value: 8.2, __typename: 'Stat' },
                    { category: 'FGM', value: 5.6, __typename: 'Stat' },
                    { category: 'FTA', value: 5.5, __typename: 'Stat' },
                    { category: 'FTM', value: 3.4, __typename: 'Stat' },
                    { category: '3PM', value: 0, __typename: 'Stat' },
                    { category: 'RPG', value: 13.7, __typename: 'Stat' },
                    { category: 'APG', value: 1.5, __typename: 'Stat' },
                    { category: 'PPG', value: 14.7, __typename: 'Stat' },
                    { category: 'SPG', value: 0.8, __typename: 'Stat' },
                    { category: 'BPG', value: 1.8, __typename: 'Stat' },
                    { category: 'TPG', value: 2.2, __typename: 'Stat' },
                ],
            },
            {
                id: '9296',
                firstName: 'Mike',
                lastName: 'Conley',
                fullName: 'Mike Conley',
                currentTeam: { abbreviation: 'UTA', __typename: 'NbaTeam' },
                position: 'PG',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201144.png',
                __typename: 'Player',
                stats: [
                    { category: 'FGA', value: 12.5, __typename: 'Stat' },
                    { category: 'FGM', value: 4.6, __typename: 'Stat' },
                    { category: 'FTA', value: 3.5, __typename: 'Stat' },
                    { category: 'FTM', value: 2.8, __typename: 'Stat' },
                    { category: '3PM', value: 1.9, __typename: 'Stat' },
                    { category: 'RPG', value: 3.5, __typename: 'Stat' },
                    { category: 'APG', value: 4.6, __typename: 'Stat' },
                    { category: 'PPG', value: 13.9, __typename: 'Stat' },
                    { category: 'SPG', value: 0.8, __typename: 'Stat' },
                    { category: 'BPG', value: 0.2, __typename: 'Stat' },
                    { category: 'TPG', value: 2.1, __typename: 'Stat' },
                ],
            },
            {
                id: '9244',
                firstName: 'Montrezl',
                lastName: 'Harrell',
                fullName: 'Montrezl Harrell',
                currentTeam: { abbreviation: 'LAC', __typename: 'NbaTeam' },
                position: 'PF',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1626149.png',
                __typename: 'Player',
                stats: [
                    { category: 'FGA', value: 13.1, __typename: 'Stat' },
                    { category: 'FGM', value: 7.7, __typename: 'Stat' },
                    { category: 'FTA', value: 5.2, __typename: 'Stat' },
                    { category: 'FTM', value: 3.3, __typename: 'Stat' },
                    { category: '3PM', value: 0, __typename: 'Stat' },
                    { category: 'RPG', value: 7.6, __typename: 'Stat' },
                    { category: 'APG', value: 2, __typename: 'Stat' },
                    { category: 'PPG', value: 18.7, __typename: 'Stat' },
                    { category: 'SPG', value: 0.7, __typename: 'Stat' },
                    { category: 'BPG', value: 1.1, __typename: 'Stat' },
                    { category: 'TPG', value: 1.7, __typename: 'Stat' },
                ],
            },
            {
                id: '9338',
                firstName: 'Ricky',
                lastName: 'Rubio',
                fullName: 'Ricky Rubio',
                currentTeam: { abbreviation: 'PHX', __typename: 'NbaTeam' },
                position: 'PG',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201937.png',
                __typename: 'Player',
                stats: [
                    { category: 'FGA', value: 11.9, __typename: 'Stat' },
                    { category: 'FGM', value: 4.6, __typename: 'Stat' },
                    { category: 'FTA', value: 3.3, __typename: 'Stat' },
                    { category: 'FTM', value: 2.8, __typename: 'Stat' },
                    { category: '3PM', value: 1.1, __typename: 'Stat' },
                    { category: 'RPG', value: 4.6, __typename: 'Stat' },
                    { category: 'APG', value: 9.2, __typename: 'Stat' },
                    { category: 'PPG', value: 13.2, __typename: 'Stat' },
                    { category: 'SPG', value: 1.3, __typename: 'Stat' },
                    { category: 'BPG', value: 0.2, __typename: 'Stat' },
                    { category: 'TPG', value: 2.1, __typename: 'Stat' },
                ],
            },
            {
                id: '15204',
                firstName: 'Wendell',
                lastName: 'Carter Jr.',
                fullName: 'Wendell Carter Jr.',
                currentTeam: { abbreviation: 'CHI', __typename: 'NbaTeam' },
                position: 'C',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1628976.png',
                __typename: 'Player',
                stats: [
                    { category: 'FGA', value: 8.1, __typename: 'Stat' },
                    { category: 'FGM', value: 4.6, __typename: 'Stat' },
                    { category: 'FTA', value: 3.7, __typename: 'Stat' },
                    { category: 'FTM', value: 2.7, __typename: 'Stat' },
                    { category: '3PM', value: 0.1, __typename: 'Stat' },
                    { category: 'RPG', value: 9.9, __typename: 'Stat' },
                    { category: 'APG', value: 1, __typename: 'Stat' },
                    { category: 'PPG', value: 11.9, __typename: 'Stat' },
                    { category: 'SPG', value: 0.8, __typename: 'Stat' },
                    { category: 'BPG', value: 0.7, __typename: 'Stat' },
                    { category: 'TPG', value: 1.4, __typename: 'Stat' },
                ],
            },
            {
                id: '10151',
                firstName: 'Tomas',
                lastName: 'Satoransky',
                fullName: 'Tomas Satoransky',
                currentTeam: { abbreviation: 'CHI', __typename: 'NbaTeam' },
                position: 'PG',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203107.png',
                __typename: 'Player',
                stats: [
                    { category: 'FGA', value: 7.6, __typename: 'Stat' },
                    { category: 'FGM', value: 3.3, __typename: 'Stat' },
                    { category: 'FTA', value: 1.7, __typename: 'Stat' },
                    { category: 'FTM', value: 1.5, __typename: 'Stat' },
                    { category: '3PM', value: 1.1, __typename: 'Stat' },
                    { category: 'RPG', value: 3.3, __typename: 'Stat' },
                    { category: 'APG', value: 5.3, __typename: 'Stat' },
                    { category: 'PPG', value: 9.3, __typename: 'Stat' },
                    { category: 'SPG', value: 1.4, __typename: 'Stat' },
                    { category: 'BPG', value: 0.1, __typename: 'Stat' },
                    { category: 'TPG', value: 2.1, __typename: 'Stat' },
                ],
            },
        ],
        __typename: 'Team',
    },
}

export const weeklyOverviewData = {
    myTeam: {
        players: [
            {
                id: '9158',
                firstName: 'LeBron',
                lastName: 'James',
                fullName: 'LeBron James',
                currentTeam: { abbreviation: 'LAL', __typename: 'NbaTeam' },
                position: 'SF',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/2544.png',
                __typename: 'Player',
                gameCountThisWeek: 3,
                injury: null,
            },
            {
                id: '9082',
                firstName: 'Al',
                lastName: 'Horford',
                fullName: 'Al Horford',
                currentTeam: { abbreviation: 'PHI', __typename: 'NbaTeam' },
                position: 'C',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201143.png',
                __typename: 'Player',
                gameCountThisWeek: 4,
                injury: {
                    playingProbability: 'questionable',
                    description: 'hamstring',
                    __typename: 'Injury',
                },
            },
            {
                id: '9329',
                firstName: 'Jabari',
                lastName: 'Parker',
                fullName: 'Jabari Parker',
                currentTeam: { abbreviation: 'ATL', __typename: 'NbaTeam' },
                position: 'PF',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203953.png',
                __typename: 'Player',
                gameCountThisWeek: 4,
                injury: null,
            },
            {
                id: '9503',
                firstName: 'Rudy',
                lastName: 'Gobert',
                fullName: 'Rudy Gobert',
                currentTeam: { abbreviation: 'UTA', __typename: 'NbaTeam' },
                position: 'C',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203497.png',
                __typename: 'Player',
                gameCountThisWeek: 3,
                injury: null,
            },
            {
                id: '9296',
                firstName: 'Mike',
                lastName: 'Conley',
                fullName: 'Mike Conley',
                currentTeam: { abbreviation: 'UTA', __typename: 'NbaTeam' },
                position: 'PG',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201144.png',
                __typename: 'Player',
                gameCountThisWeek: 3,
                injury: {
                    playingProbability: 'out',
                    description: 'hamstring',
                    __typename: 'Injury',
                },
            },
            {
                id: '9244',
                firstName: 'Montrezl',
                lastName: 'Harrell',
                fullName: 'Montrezl Harrell',
                currentTeam: { abbreviation: 'LAC', __typename: 'NbaTeam' },
                position: 'PF',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1626149.png',
                __typename: 'Player',
                gameCountThisWeek: 4,
                injury: null,
            },
            {
                id: '9338',
                firstName: 'Ricky',
                lastName: 'Rubio',
                fullName: 'Ricky Rubio',
                currentTeam: { abbreviation: 'PHX', __typename: 'NbaTeam' },
                position: 'PG',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201937.png',
                __typename: 'Player',
                gameCountThisWeek: 3,
                injury: null,
            },
            {
                id: '15204',
                firstName: 'Wendell',
                lastName: 'Carter Jr.',
                fullName: 'Wendell Carter Jr.',
                currentTeam: { abbreviation: 'CHI', __typename: 'NbaTeam' },
                position: 'C',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1628976.png',
                __typename: 'Player',
                gameCountThisWeek: 4,
                injury: {
                    playingProbability: 'probable',
                    description: 'abdominal',
                    __typename: 'Injury',
                },
            },
            {
                id: '10151',
                firstName: 'Tomas',
                lastName: 'Satoransky',
                fullName: 'Tomas Satoransky',
                currentTeam: { abbreviation: 'CHI', __typename: 'NbaTeam' },
                position: 'PG',
                imageSrc:
                    'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203107.png',
                __typename: 'Player',
                gameCountThisWeek: 4,
                injury: {
                    playingProbability: 'probable',
                    description: 'toe',
                    __typename: 'Injury',
                },
            },
        ],
        __typename: 'Team',
    },
}
