version: '3'
services:
    server-local:
        build:
            context: .
            dockerfile: ./Dockerfile
        depends_on:
            - prisma
            - postgres
        restart: always
        environment:
            - PRISMA_ENDPOINT=${LOCAL_PRISMA_ENDPOINT}
        volumes:
            - ./:/app
        ports:
            - 4000:4000
    prisma:
        image: prismagraphql/prisma:1.34
        restart: always
        ports:
            - '4466:4466'
        environment:
            PRISMA_CONFIG: |
                port: 4466
                databases:
                  default:
                    connector: postgres
                    host: postgres
                    port: 5432
                    user: prisma
                    password: prisma
    postgres:
        image: postgres:10.3
        restart: always
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    postgres: ~
