version: '3'
services:
    server:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: statcat_server
        depends_on:
            - postgres
        restart: always
        environment:
            - APP_SECRET=${APP_SECRET}
            - sportsFeedUsername=${sportsFeedUsername}
            - sportsFeedPassword=${sportsFeedPassword}
            - sportsFeedUrl=${sportsFeedUrl}
            - DATABASE_URL=${DATABASE_URL}
        volumes:
            - ./src:/usr/src/app/src
            - ./prisma:/usr/src/app/prisma
        ports:
            - 4000:4000
    postgres:
        image: postgres:10.3
        restart: always
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    postgres: ~
