version: '3'
services:
    server:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: statcat_server
        depends_on:
            - prisma
            - postgres
        restart: always
        environment:
            - PRISMA_ENDPOINT=${LOCAL_PRISMA_ENDPOINT}
            - APP_SECRET=${APP_SECRET}
            - sportsFeedUsername=${sportsFeedUsername}
            - sportsFeedPassword=${sportsFeedPassword}
            - sportsFeedUrl=${sportsFeedUrl}
        volumes:
            - ./src:/usr/src/app/src
            - ./prisma:/usr/src/app/prisma
        ports:
            - 4000:4000
    prisma:
        image: prismagraphql/prisma:1.34
        restart: always
        ports:
            - '4466:4466'
        environment:
            PRISMA_CONFIG: |
                port: 4466
                databases:
                  default:
                    connector: postgres
                    host: postgres
                    port: 5432
                    user: prisma
                    password: prisma
    postgres:
        image: postgres:10.3
        restart: always
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    postgres: ~
